services:
  agent:
    image: ${UCB_CONTAINER_REGISTRY}agent-environment:1.0.7
    #build:
    #  #context: ../../../containers/agent/
    init: true
    volumes:
    - ${DYNAMIC_FILE_DIR-/dev/null}:/app_ro
    x-default: true
    environment:
    - alice=alice
    - bob=bob
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
  alice:
    image: ${UCB_CONTAINER_REGISTRY}walking-to-the-sea-side:1.0.1
    init: true
    environment:
    - USERNAME=alice
    user: 1337:1337
    volumes:
    - sage_writable_alice:/sage_writable
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    #build:
      #context: ./victim
  bob:
    image: ${UCB_CONTAINER_REGISTRY}walking-to-the-sea-side:1.0.1
    init: true
    environment:
    - USERNAME=bob
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    #build:
      #context: ./victim
volumes:
  sage_writable_alice: null
