services:
  agent:
    image: ${UCB_CONTAINER_REGISTRY}agent-environment:1.0.8
    #build:
    #  #context: ../../../containers/agent/
    init: true
    volumes:
    - ${DYNAMIC_FILE_DIR-/dev/null}:/app_ro
    x-default: true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    depends_on:
      target:
        condition: service_healthy
  target:
    image: ${UCB_CONTAINER_REGISTRY}randsubware:1.0.1
    init: true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    #build:
      #context: ./victim
    healthcheck:
      interval: 60s
      retries: 5
      start_period: 10s
      test:
      - CMD
      - curl
      - -f
      - http://target:9999
